---
- name: ansible-role-mysql
  hosts: localhost
  become: true
  gather_facts: true

  roles:
    - role: ansible-role-mysql 
      mysql_port: 3307
      mysql_databases:
        - name: zeilvoortgang
          encoding: utf8
          collation: utf8_bin
        # - name: my_imported_db
        #   # This file will be imported once at creation of the database.
        #   initial_import: /path/to/dump.sql  # .gz or also allowed.
      mysql_users:
        - name: zeilvoortgang
          password: zeilvoortgang
          priv: "zeilvoortgang.*:ALL"
          update_password: on_create