---
- name: ansible-role-mysql
  hosts: localhost
  become: true
  gather_facts: true

  roles:
    - name: Assemble from fragments from a directory
      ansible.builtin.assemble:
        src: ~/zeilvoortgang/src/main/resources/sql
        dest: ~/ansible/roles/ansible-role-mysql/files/import.sql

    - role: ansible-role-mysql 
      mysql_port: 3307
      mysql_databases:
        - name: zeilvoortgang
          encoding: utf8
          collation: utf8_bin
        - name: my_imported_db
          initial_import: ~/ansible/roles/ansible-role-mysql/files/import.sql
      mysql_users:
        - name: zeilvoortgang
          password: zeilvoortgang
          priv: "zeilvoortgang.*:ALL"
          update_password: on_create