---
- name: Install Maven
  ansible.builtin.yum:
    name: maven
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Maven (Debian-based)
  ansible.builtin.apt:
    name: maven
    state: present
  when: ansible_os_family == "Debian"

#- name: Ensure Java is installed
#  ansible.builtin.package:
#    name: openjdk-11-jdk
#    state: present

#- name: Copy Maven settings (optional)
#  ansible.builtin.copy:
#    src: settings.xml
#    dest: /root/.m2/settings.xml
#    owner: root
#    group: root
#    mode: '0644'

- name: Build application JAR
  ansible.builtin.command:
    cmd: mvn clean package
    chdir: ~/zeilvoortgang

- name: mkdir appplication directory
  ansible.builtin.file:
    path: /opt/zeilvoortgang
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy JAR file to deployment directory
  ansible.builtin.copy:
    src: ~/zeilvoortgang/target/zeilvoortgang*-SNAPSHOT.jar
    dest: /opt/zeilvoortgang/zeilvoortgang.jar
    owner: root
    group: root
    mode: '0755'
