---
- name: Install Maven
  ansible.builtin.yum:
    name: maven
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Maven (Debian-based)
  ansible.builtin.apt:
    name: maven
    state: present
  when: ansible_os_family == "Debian"

- name: Build zeilvoortgang JAR
  ansible.builtin.command:
    cmd: mvn clean package
    chdir: ~/zeilvoortgang

- name: mkdir zeilvoortgang directory
  ansible.builtin.file:
    path: /opt/zeilvoortgang
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy JAR file to deployment directory
  copy:
    src: "{{ item }}"
    dest: /opt/zeilvoortgang/zeilvoortgang.jar
    owner: root
    group: root
    remote_src: yes
    mode: 0755
  with_fileglob:
    - "~/zeilvoortgang/target/zeilvoortgang*-SNAPSHOT.jar"

