---
- name: ansible-role-mysql
  hosts: localhost
  become: true
  gather_facts: true

  roles:
    - role: createTablesSQL

    - role: ansible-role-mysql 
      mysql_port: 3306
      mysql_databases:
        - name: zeilvoortgang
          encoding: utf8
          collation: utf8_bin
        - name: zeilvoortgang
          initial_import: ~/ansible/roles/ansible-role-mysql/files/import.sql
      mysql_users:
        - name: zeilvoortgang
          password: zeilvoortgang
          priv: "zeilvoortgang.*:ALL"
          update_password: on_create

    - role: ansible-java

    - role: build_zeilvoortgang

    - role: run_zeilvoortgang