---
- name: Copy application JAR
  ansible.builtin.copy:
    src: application.jar
    dest: /opt/application/application.jar
    owner: root
    group: root
    mode: '0755'

- name: Create systemd service file
  ansible.builtin.template:
    src: application.service.j2
    dest: /etc/systemd/system/application.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start application service
  ansible.builtin.systemd:
    name: application
    enabled: yes
    state: started
