---
- name: Copy zeilvoortgang JAR
  ansible.builtin.copy:
    src: zeilvoortgang.jar
    dest: /opt/zeilvoortgang/zeilvoortgang.jar
    owner: root
    group: root
    mode: '0755'

- name: Create systemd service file
  ansible.builtin.template:
    src: zeilvoortgang.service.j2
    dest: /etc/systemd/system/zeilvoortgang.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start zeilvoortgang service
  ansible.builtin.systemd:
    name: zeilvoortgang
    enabled: yes
    state: started
