jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ...existing code...
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      # ...existing code...